import { Injectable } from "@angular/core";
import {Http, Headers, RequestOptions} from '@angular/http';
import { environment } from "../../environments/environment";
import { CognitoUserPool } from "amazon-cognito-identity-js";
import * as AWS from "aws-sdk/global";
import * as awsservice from "aws-sdk/lib/service";
import { CognitoCallback, CognitoUtil, LoggedInCallback } from "./cognito.service";
import { resolve } from "dns";

@Injectable()
export class LocalDataService {

  constructor() {

  }

  getRankedKeywords() {
    return [
      {
        "domain": "humphreysmedia.com",
        "country_code": "US",
        "language": "en",
        "key": "seo company in columbus",
        "exact_domain": "humphreysmedia.com",
        "position": 17,
        "url": "https://humphreysmedia.com/locations/columbus-ohio/",
        "relative_url": "/locations/columbus-ohio/",
        "results_count": 11200000,
        "etv": 0,
        "traffic_cost": 0,
        "competition": 0.011904,
        "cpc": 0,
        "date": "2018-08-13T00:00:00+00:00",
        "extra": "videos",
        "search_volume": 50,
        "spell": "",
        "title": "Columbus Ohio SEO Company | Humphreys Media | Internet ...",
        "snippet": "Sep 12, 2017 - We are the premier SEO and digital marketing company that provides Columbus based companies with only the best service that brings results."
      },
      {
        "domain": "humphreysmedia.com",
        "country_code": "US",
        "language": "en",
        "key": "seo company columbus",
        "exact_domain": "humphreysmedia.com",
        "position": 18,
        "url": "https://humphreysmedia.com/locations/columbus-ohio/",
        "relative_url": "/locations/columbus-ohio/",
        "results_count": 5250000,
        "etv": 0,
        "traffic_cost": 0,
        "competition": 0.165413,
        "cpc": 0,
        "date": "2018-08-12T00:00:00+00:00",
        "extra": "videos",
        "search_volume": 50,
        "spell": "",
        "title": "Columbus Ohio SEO Company | Humphreys Media | Internet ...",
        "snippet": "Sep 12, 2017 - We are the premier SEO and digital marketing company that provides Columbus based companies with only the best service that brings results."
      },
      {
        "domain": "humphreysmedia.com",
        "country_code": "US",
        "language": "en",
        "key": "seo company columbus ohio",
        "exact_domain": "humphreysmedia.com",
        "position": 19,
        "url": "https://humphreysmedia.com/locations/columbus-ohio/",
        "relative_url": "/locations/columbus-ohio/",
        "results_count": 380000,
        "etv": 0,
        "traffic_cost": 0,
        "competition": 0.194379,
        "cpc": 30.0039,
        "date": "2018-08-30T00:00:00+00:00",
        "extra": "videos",
        "search_volume": 40,
        "spell": "",
        "title": "Columbus Ohio SEO Company | Humphreys Media | Internet ...",
        "snippet": "Sep 12, 2017 - We are the premier SEO and digital marketing company that provides Columbus based companies with only the best service that brings results."
      },
      {
        "domain": "humphreysmedia.com",
        "country_code": "US",
        "language": "en",
        "key": "ppc management agency columbus ohio",
        "exact_domain": "humphreysmedia.com",
        "position": 20,
        "url": "https://humphreysmedia.com/locations/columbus-ohio/",
        "relative_url": "/locations/columbus-ohio/",
        "results_count": 92,
        "etv": 0,
        "traffic_cost": 0,
        "competition": 0,
        "cpc": 0,
        "date": "2018-08-30T00:00:00+00:00",
        "extra": "images",
        "search_volume": 0,
        "spell": "",
        "title": "Columbus Ohio SEO Company | Humphreys Media | Internet ...",
        "snippet": "Sep 12, 2017 - Columbus Based SEO Company to Help You Grow Your Business Online ... count with Humphreys Media's Google PPC management service."
      },
      {
        "domain": "humphreysmedia.com",
        "country_code": "US",
        "language": "en",
        "key": "local seo columbus ohio",
        "exact_domain": "humphreysmedia.com",
        "position": 21,
        "url": "https://humphreysmedia.com/locations/columbus-ohio/",
        "relative_url": "/locations/columbus-ohio/",
        "results_count": 4330000,
        "etv": 0,
        "traffic_cost": 0,
        "competition": 0.231292,
        "cpc": 0,
        "date": "2018-08-18T00:00:00+00:00",
        "extra": "videos",
        "search_volume": 40,
        "spell": "",
        "title": "Columbus Ohio SEO Company | Humphreys Media | Internet ...",
        "snippet": "Sep 12, 2017 - Columbus Based SEO Company to Help You Grow Your Business ... We're local to the Ohio area and can get you the SEO rankings your ..."
      },
      {
        "domain": "humphreysmedia.com",
        "country_code": "US",
        "language": "en",
        "key": "small business seo agency columbus ohio",
        "exact_domain": "humphreysmedia.com",
        "position": 21,
        "url": "https://humphreysmedia.com/locations/columbus-ohio/",
        "relative_url": "/locations/columbus-ohio/",
        "results_count": 2940000,
        "etv": 0,
        "traffic_cost": 0,
        "competition": 0,
        "cpc": 0,
        "date": "2018-08-25T00:00:00+00:00",
        "extra": "",
        "search_volume": 0,
        "spell": "",
        "title": "Columbus Ohio SEO Company | Humphreys Media | Internet ...",
        "snippet": "Sep 12, 2017 - Columbus Based SEO Company to Help You Grow Your Business ... We are the premier SEO and digital marketing company that provides Columbus based ... At Humphreys Media, we strive to help small businesses gain the ..."
      },
      {
        "domain": "humphreysmedia.com",
        "country_code": "US",
        "language": "en",
        "key": "seo firm columbus ohio",
        "exact_domain": "humphreysmedia.com",
        "position": 22,
        "url": "https://humphreysmedia.com/locations/columbus-ohio/",
        "relative_url": "/locations/columbus-ohio/",
        "results_count": 2160000,
        "etv": 0,
        "traffic_cost": 0,
        "competition": 0,
        "cpc": 0,
        "date": "2018-08-30T00:00:00+00:00",
        "extra": "videos,local_pack",
        "search_volume": 0,
        "spell": "",
        "title": "Columbus Ohio SEO Company | Humphreys Media | Internet ...",
        "snippet": "Sep 12, 2017 - We are the premier SEO and digital marketing company that provides Columbus based companies with only the best service that brings results."
      },
      {
        "domain": "humphreysmedia.com",
        "country_code": "US",
        "language": "en",
        "key": "ohio seo company",
        "exact_domain": "humphreysmedia.com",
        "position": 23,
        "url": "https://humphreysmedia.com/locations/columbus-ohio/",
        "relative_url": "/locations/columbus-ohio/",
        "results_count": 1060000,
        "etv": 0,
        "traffic_cost": 0,
        "competition": 0.00909,
        "cpc": 0,
        "date": "2018-08-27T00:00:00+00:00",
        "extra": "",
        "search_volume": 10,
        "spell": "",
        "title": "Columbus Ohio SEO Company | Humphreys Media | Internet ...",
        "snippet": "Sep 12, 2017 - We are the premier SEO and digital marketing company that provides Columbus based companies with only the best service that brings results."
      },
      {
        "domain": "humphreysmedia.com",
        "country_code": "US",
        "language": "en",
        "key": "seo service columbus ohio",
        "exact_domain": "humphreysmedia.com",
        "position": 25,
        "url": "https://humphreysmedia.com/locations/columbus-ohio/",
        "relative_url": "/locations/columbus-ohio/",
        "results_count": 4780000,
        "etv": 0,
        "traffic_cost": 0,
        "competition": 0,
        "cpc": 0,
        "date": "2018-08-30T00:00:00+00:00",
        "extra": "local_pack",
        "search_volume": 0,
        "spell": "",
        "title": "Columbus Ohio SEO Company | Humphreys Media | Internet ...",
        "snippet": "Sep 12, 2017 - We are the premier SEO and digital marketing company that provides Columbus based companies with only the best service that brings results."
      },
      {
        "domain": "humphreysmedia.com",
        "country_code": "US",
        "language": "en",
        "key": "seo services columbus oh",
        "exact_domain": "humphreysmedia.com",
        "position": 26,
        "url": "https://humphreysmedia.com/locations/columbus-ohio/",
        "relative_url": "/locations/columbus-ohio/",
        "results_count": 3380000,
        "etv": 0,
        "traffic_cost": 0,
        "competition": 0,
        "cpc": 0,
        "date": "2018-08-21T00:00:00+00:00",
        "extra": "local_pack",
        "search_volume": 0,
        "spell": "",
        "title": "Columbus Ohio SEO Company | Humphreys Media | Internet ...",
        "snippet": "Sep 12, 2017 - We are the premier SEO and digital marketing company that provides Columbus based companies with only the best service that brings results."
      }
    ]
  }

};